/**
 * Bismi Broilers — Cloudinary CDN Image Mapping
 * Auto-generated by scripts/upload-to-cloudinary.mjs
 * 
 * Cloud Name: dj1tmb6yr
 * All URLs use f_auto,q_auto for optimal mobile performance and minimal bandwidth.
 */

export const CLOUDINARY_BASE_URL = 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto';

export const CloudinaryImages = {
    /** Chicken Curry Cut */
    curryCuts: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/curry-cuts',

    /** Chicken Biriyani Cut */
    biryaniCut: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/biryani-cut',

    /** Chicken Boneless Cubes */
    bonelessCubes: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/boneless-cubes',

    /** Chicken Boneless */
    chickenBoneless: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/chicken-boneless',

    /** Chicken Breast */
    chickenBreasts: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/chicken-breasts',

    /** Chicken Small Curry Cut */
    curryCutSmall: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/curry-cut-small',

    /** Chicken Gravy Cut */
    curryCutLarge: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/curry-cut-large',

    /** Chicken Drumsticks */
    drumsticks: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/drumsticks',

    /** Chicken Gravy Cut (Webp) */
    gravyCut: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/gravy-cut',

    /** Chicken Leg Piece */
    legPiece: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/leg-piece',

    /** Chicken Wings */
    chickenWings: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/chicken-wings',

    /** Chicken Lollipop */
    chickenLollipop: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/chicken-lollipop',

    /** Chicken Keema */
    chickenKeema: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/chicken-keema',

    /** Raw Whole Chicken */
    rawWholeChicken: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/raw-whole-chicken',

    /** Country Chicken (Naatu Kozhi) */
    countryChicken: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/country-chicken',

    /** White Egg */
    whiteEgg: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/chicken/white-egg',

    /** Kaadai (Farm Quail) */
    quailMeat: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/kadai/quail-meat',

    /** Kaadai Egg (Quail Egg) */
    quailEgg: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/products/kadai/quail-egg',

    /** Category Chicken */
    categoryChicken: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/categories/chicken',

    /** Category Kaadai */
    categoryKadai: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/categories/kadai',

    /** 3D Speed Delivery Rider */
    bannerSpeedDeliveryRider: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/mobile/banners/speed-delivery-rider',

    /** Sunday Biryani Cutout */
    bannerBiryaniCutout: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/mobile/banners/biryani-cutout',

    /** Offer Coupon Cutout */
    bannerCouponCutout: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/mobile/banners/coupon-cutout',

    /** Delivery Guy Scooter */
    scooterDeliveryGuy: 'https://res.cloudinary.com/dj1tmb6yr/image/upload/f_auto,q_auto,w_600,c_limit/bismi/mobile/banners/delivery-guy-scooter',
} as const;

export type CloudinaryImageKey = keyof typeof CloudinaryImages;
